package com.example.tictactoehpv3;

import java.util.Random;

public class Tasks {

    private BoardView boardView;
    private hiddenGameActivity activityhidden;

    public Tasks(){
    }

    public void setHiddenGameActivity(hiddenGameActivity a) {
        activityhidden = a;
    }

    public String dares(){
        return "The opposing team gives you a dare to complete in 30 seconds. Complete the dare or take a drink.";
    }

    public String truth(){
        return "The opposing team asks you a question. You must answer truthfully or drink.";
    }

    public String charades(){
        String []charadesList = {   "King Kong",
                                    "Iron Man",
                                    "Baywatch",
                                    "moping the floor",
                "car racing",
                "giving birth",
                "rabbit",
                "kangaroo",
                "Spiderman",
                "puppet",
                "haircut",
                "trumpet",
                "shopping cart",
                "lipstick",
                "shower",
                "hula hoop",
                "eating a banana",
                "see-saw",
                "peel",
                "opera singer",
                "think",
                "whisper",
                "yo-yo",
                "bobsled",
                "quicksand",
                "steeping tea",
                "trip",
                "killer",
                "bubble",
                "faucet",
                                    "The Walking Dead",
                                    "Riding a unicycle",
                                    "Doing the Backstroke",
                                    "Running on a treadmill",
                                    "Flying in a plane through turbulence",
                                    "Winning an award",
                                    "Gardening",
                                    "Sailing",
                                    "Prostitute",
                                    "Nightmare",
                                    "Spider",
                                    "Waterfall",
                                    "standing ovation",
                                    "flag",
                                    "fizzing a drink",
                                    "lawn mower",
                                    "softball",
                                    "wig",
                                    "stain",
                                    "hair dryer",
                                    "sip",
                                    "huddle",
                                    "cowboy",
                                    "knot",
                                    "president",
                                    "quicksand",
                                    "spine",
                                    "chess",
                                    "doing laundry",
                                    "erasing what you've written",
                                    "opening a jar",
                                    "cramp",
                                    "flamingo",
                                    "wood pecker",
                                    "honk",
                                    "writing on a blackboard",
                                    "gym"
                            };
        Random random = new Random();
        int num = random.nextInt(charadesList.length-1);
        return charadesList[num];
    }

    public String[] taboo(){
        String [][]tabooList = {{"Dollars", "Cents", "Pennies", "Money", "Cash", "USA"},
                {"Mediator", "Listen", "Dispute", "Problem", "Settle", "Peer"},
                {"Robbery", "Thief", "Invasion", "Steal", "Take", "Home"},
                {"Black Market", "Color", "Super", "Buy", "Sell", "Illegal"},
                {"Partner", "Husband", "Companion", "Wife", "Boss", "Head"},
                {"Seems", "Appear", "Looks", "Imagine", "Time", "Thought"},
                {"Dairy", "Milk", "Cheese", "Cow", "Product", "Lactose"},
                {"Caesar", "King", "Rome", "Hotel", "Salad", "Little"},
                {"Magazine", "Mail", "Weekly", "Read", "Advertisement", "Subscriptions"},
                {"BUILDING", "HOME", "SKYSCRAPER", "OFFICE", "WORK", "EMPIRE STATE"},
                {"DESK", "WORK", "TOP", "STUDY", "OFFICE", "PAPERS"},
                {"GALAXY", "SUN", "SYSTEM", "SPACE", "EARTH", "MILKY WAY"},
                {"APPLE", "COMPUTER", "STEVE JOBS", "FRUIT", "ORANGE", "RED"},
                {"MARBLES", "BALLS", "SMALL", "ROLL", "STRIKE", "GAME"},
                {"SNEEZE", "NOSE", "SICK", "ILL", "PEPPER", "COUGH"},
                {"CERTIFICATE", "AWARD", "PAPER", "TROPHY", "BIRTH", "COMPLETE"},
                {"GENRE", "CATEGORY", "MOVIE", "MUSIC", "TYPE", "CLASSIFY"},
                {"ASHLEY OLSEN", "TWINS", "FULL HOUSE", "COMEDY", "SHOW", "FAMOUS"},
                {"WEATHER", "RAIN", "OUTSIDE", "METEOROLOGIST", "PREDICT", "FORECAST"},
                {"PINKY", "THUMB", "FINGER", "HAND", "TOE", "RING"},
                {"PREGNANT", "BABY", "KIDS", "DELIVERY", "NINE MONTHS", "BELLY"},
                {"LOCHNESS", "SEA", "MONSTER", "WATER", "MYTH", "LEGEND"},
                {"FISH", "WATER", "ANIMALS", "OCEAN", "LAKE", "POND"},
                {"SUPERMAN", "HERO", "MOVIE", "FLIES", "KRYPTONITE", "UNDERWEAR"},
                {"ATTIC", "UPSTAIRS", "STORAGE", "HOUSE", "HOME", "FINISH"},
                {"DEFENDANT", "PROSECUTION", "COURT", "LAW", "JUDGE", "ATTORNEY"},
                {"E-MAIL", "ONLINE", "ELECTRONIC", "SEND", "FAST", "INTERNET"},
                {"STORM", "WET", "WATER", "DRIZZLE", "POUR", "UMBRELLA"},
                {"FLUSH", "TOILET", "POKER", "SUIT", "BATHROOM", "ROYAL"},
                {"MORTGAGE", "OWN", "LOAN", "DEBT", "HOME", "RENT"},
                {"DRAWER", "CLOTHES", "OPEN", "CLOSE", "STORE", "CLOSET"},
                {"REFRIGERATOR", "COLD", "STORE", "FOOD", "KEEP", "DOORS"},
                {"SUITCASE", "TRAVEL", "AIRPORT", "PACK", "LUGGAGE", "BAG"},
                {"UNIVERSITY", "COLLEGE", "HIGH SCHOOL", "STUDY", "DEGREE", "ACADEMIC"},
                {"SHIRT", "BUTTON", "WEAR", "TEE", "TOP", "BLOUSE"},
                {"SNAKE", "ANIMAL", "LONG", "COBRA", "VENOM", "POISON"},
                {"PRESENTATION", "POWERPOINT", "SHOW", "DISPLAY", "REVIEW", "ORAL"},
                {"MOUTHWASH", "BRUSH", "RINSE", "TEETH", "DENTIST", "CAVITY"},
                {"CREDIT CARD", "WALLET", "PAY", "CASH", "CARRY", "PURCHASE"}};
        Random random = new Random();
        int num = random.nextInt(tabooList.length-1);
        return tabooList[num];
    }

    public String pictionary(){
        String []pictionaryList = {"shopping cart", "lightsaber", "pitchfork", "drumstick", "oven", "eye", "penny farthing",
        "crown", "rat", "submarine", "top", "sit-up", "giving-birth", "baby-sitter", "farmer", "torch", "banana split",
        "grave", "pilot", "DJ", "singer", "library", "light bulb", "paint", "gingerbread man", "pot", "lamp", "lunchbox", "baseball",
        "flagpole", "gas", "popsicle", "extension chord", "circus", "wedge", "slope", "wallet", "milk", "winter", "photograph", "trash can",
        "popsicle", "sword", "notepad", "hair dryer", "ski", "button", "alarm clock", "bottle", "finger", "backpack", "sunglasses",
        "boy", "fish", "skateboard", "ring", "crab", "smile", "mouth", "bear", "lollipop", "uni-cycle", "armour", "shoes", "family",
        "cupcake", "neck", "elephant", "spooning", "cherry", "cat", "crayon", "window", "helicopter", "football", "hook"};
        Random random = new Random();
        int num = random.nextInt(pictionaryList.length -1);
        return pictionaryList[num];
    }

    public String[] question(){
        String [][]questionList = {{"Which cult TV show from the 1990’s, featuring David Duchovny and Gillian Anderson, was resurrected in 2016?", "The X-Files."},
                {"Which actor made his debut as James Bond in the film Casino Royale in 2006?", "Daniel Craig."},
                {"In which city where the 2016 summer Olympics held?", "Rio, Brazil"},
                {"Who is the oldest of the Kardashian sisters?", "Kourtney"},
                {"The character Jar Jar Binks first appears in which of the Star Wars movies?", "Star Wars Episode 1 – The Phantom Menace."},
                {"Which leading fashion designer was found dead in his London home in February, 2010?", "Alexander McQueen."},
                {"Who won the 2016 Grammy for Album of the Year?", "Taylor Swift"},
                {"Which song topped the Billboard charts for 14 consecutive weeks in 2015?", "Uptown Funk by Mark Ronson featuring Bruno Mars."},
                {"Who won the 2016 Best Actor Oscar?", "Leonardo di Caprio for his role in The Revenant."},
                {"What is Eleven's real name in Stranger Things?", "Jane"},
                {"In Arrested Development, where is there always money?", "The Banana Stand"},
                {"What USA Network TV show did Meghan Markle appear in for seven seasons?", "Suits"},
                {"The Pearson family in This Is Us are famously fans of what NFL team?", "The Pittsburgh Steelers"},
                {"Who wrote the novel that inspired the Hulu series The Handmaid's Tale?", "Margaret Atwood"},
                {"How are Jon Snow and Daenerys related in Game of Thrones?", "Daenerys is Jon's aunt"},
                {"What is the name of \"the mother\" on How I Met Your Mother?", "Tracy McConnell"},
                {"Does Stanley Hudson from The Office have a mustache?", "Yes"},
                {"What 2004 rom-com did Brie Larson appear in as a child?", "13 Going on 30"},
                {"Put these Nicholas Sparks movies in order of oldest to most recent: The Notebook, Safe Haven, A Walk to Remember, The Last Song.", "A Walk to Remember (2002), The Notebook (2004), The Last Song (2010), Safe Haven (2013)"},
                {"What is the name of the magazine Kate Hudson's character Andie works at in How to Lose a Guy in 10 Days?", "Composure"},
                {"What movie won best picture at the 2020 Academy Awards?", "Parasite"},
                {"Name all four of Kim Kardashian and Kanye West's kids, from oldest to youngest.", "North, Saint, Chicago, Psalm"},
                {"Name the two performers who headlined the 2020 Super Bowl halftime show.", "Shakira and Jennifer Lopez"},
                {"Which celebrity couple recently named their daughter Raddix?", "Cameron Diaz and Benji Madden"},
                {"What actor is Gossip Girl star Leighton Meester married to?", "Adam Brody"},
                {"What is Katy Perry's real name?", "Katy Hudson"},
                {"Which Sex and the City star ran for political office in New York?", "Cynthia Nixon"},
                {"What are the names of Beyoncé and JAY-Z's twins?", "Rumi and Sir"},
                {"What SNL cast member is Scarlett Johansson engaged to?", "Colin Jost"},
                {"What 2000 Disney Channel Original Movie stars a Jonas Brothers ex?", "Rip Girls star Camilla Belle"},
                {"What actress played Kaitlin Cooper in Season 1 of The OC?", "Shailene Woodley"},
                {"What is Mia's full name in Princess Diaries?", "Amelia Mignonette Thermopolis Renaldi, Princess of Genovia"},
                {"What 2001 Olsen twin movie features the sisters going to the Bahamas for winter break and getting mixed up with a man smuggling stolen artifacts?", "Holiday in the Sun"},
                {"On Even Stevens, what was Ren and Louis' older brother's name?", "Donnie"},
                {"What year did High School Musical come out?", "2006"},
                {"What was Destiny's Child originally called?", "Girl's Tyme"},
                {"Which pop diva became the first woman to win the Album of the Year Grammy twice in 2016?", "Taylor Swift"},
                {"Which ’80s pop icon tragically died the day before the Grammys in 2012?", "Whitney Houston"},
                {"Who was the first lad to leave One Direction in 2015?", "Zayn Malik "},
                {"Which rapper-mogul launched the Tidal streaming service in 2015?", "Jay-Z"},
                {"What did “Breaking Bad” DEA agent Hank Schrader collect as a hobby?", "Minerals "},
                {"A photo of what item had people arguing if it was “black and blue or white and gold?”", "Dress"},
                {"What is the origin of the “Floss Dance”?", "Backpack Kid"},
                {"A picture of what created the phrase “break the Internet”?", "Kim Kardashian’s ass"},
                {"What movie did Warren Beaty and Faye Dunaway mistakenly announce as Best Picture at the 2017 Oscars?", "La La Land"},
                {"Which actor has appeared in the most Marvel Cinematic Universe movies?", "Chris Evans"},
                {"What movie took 12 years to film?", "Boyhood"},
                {"At the end of the James Bond film “Skyfall,” which actor replaced Judi Dench as the new “M”?", "Ralph Fiennes"},
                {"What film led to North Korea sending a warning to the United States?", "The Interview"},
                {"In “The Revenant,” Leonardo DiCaprio was attacked by a ____ ?", "Bear"},
                {"Who played Belle in Disney’s live-action “Beauty and the Beast”?", "Emma Watson"},
                {"Where did 1.7m people sign up online to 'storm' in 2019 (about 1,500 turned up)?", "Area 51"},
                {"Remember everyone pouring ice buckets over themselves in 2014? Remember what they were raising awareness of?", "ALS"},
                {"Who gave us the timeless lyric, 'gotta have my bowl, gotta have cereal'?", "Rebecca Black"},
                {"What name was given to the fad of lying face down and posting pictures on social media?", "Planking"},
                {"The world did not end in December 2012, although some believed it would after interpreting which calendar?", "Mayan"},
                {"A picture of what has the most likes on instagram?", "An egg"}};
        Random random = new Random();
        int num = random.nextInt(questionList.length - 1);
        return questionList[num];
    }

    public String[] completeLyric(){
        String [][]lyricList = {{"Scoop, Muck and Dizzy and Rolly too, Lofty and Wendy, join the crew.", "Bob the Builder Can We Fix It"},
                {"To the place I belong, West Virginia, mountain momma.", "Take Me Home, Country Roads"},
                {"Stopped into a church, I passed along the way.", "California Dreaming"},
                {"For what is a man? What has he got? If not himself - Then he has naught.", "My Way"},
                {"Time can bring you down, time can bend your knees.", "Tears in Heaven"},
                {"No matter what they take from me, they can’t take away my dignity.", "The Greatest Love of All"},
                {"I could be your Buzz Lightyear, fly across the globe.", "Boyfriend"},
                {"No more will my green sea go turn a deeper blue, I could not foresee this thing happening to you.", "Paint It Black"},
                {"But February made me shiver, with every paper I'd deliver.", "American Pie"},
                {"What rhymes with hug me?", "Blurred Lines"},
                {"Been around the world, don't speak the language. But your booty don't need explaining", "Talk Dirty"},
                {"White lips, pale face, breathing in snow flakes", "The A-Team"},
                {"Sun-kissed skin, so hot, we'll melt your popsicle!", "California Girls"},
                {"What you gon' do with all that junk? All that junk inside your trunk!", "My Humps"},
                {"I like big butts and I cannot lie", "Baby got Back"},
                {"Cause if you liked it then you should have put a ring on it", "Single Ladies"},
                {"Oh, as long as I know how to love I know I’ll stay alive", "I Will Survive"},
                {"I hear babies crying, I watch them grow", "What A Wonderful World"},
                {"Take my hand, take my whole life too", "Can't Help Falling in Love"},
                {"It ain't me, it ain't me, I ain't no Senator's son, son. It ain't me, it ain't me, I ain't no fortunate one.", "Fortunate Son"},
                {"Freedom, well, that's just some people talking. Your prison is walking through this world all alone.", "Desperado"},
                {"First you get a swimming pool full of liquor, then you dive in it", "Swimming Pools (Drank)"},
                {"There she stood in the doorway I heard the mission bell", "Hotel California"},
                {"I don’t wanna talk/ About the things we’ve gone through/ Though it’s hurting me/ Now it’s history.", "The Winner Takes It All"},
                {"Love can touch us one time, and last for a lifetime, and never let go till we're gone.", "My Heart Will Go On"},
                {"You can get yourself clean, you can have a good meal, you can do what about you feel.", "Y.M.C.A."},
                {"It felt so wrong, it felt so right, don't mean I'm in love tonight.", "I Kissed a Girl"},
                {"Got in a little hometown jam, so they put a rifle in my hand.", "Born In The U.S.A."},
                {"I hate to turn up out of the blue uninvited, but I couldn't stay away, I couldn't fight it.", "Someone Like You"},
                {"Baby 'cause in the dark you can't see shiny cars and that's when you need me there, with you I'll always share.", "Umbrella"},
                {"He's a one stop shop, makes my cherry pop.", "Candyman"},
                {"Fold 'em, let 'em, hit me, raise it baby stay with me.", "Poker Face"},
                {"Well maybe there's a God above, but all I ever learned from love was how to shoot somebody who outdrew you.", "Hallelujah"},
                {"I've been roaming around, always looking down at all I see, painted faces, fill the places I can't reach.", "Use Somebody"},
                {"Remember those walls I built, well, baby, they're tumbling down.", "Halo"},
                {"Do you ever feel, feel so paper thin, like a house of cards, one blow from caving in.", "Firework)"},
                {"Wrong information always shown by the media, negative images it's the main criteria.", "Where Is the Love?"},
                {"And darling I will be loving you 'til we're 70, and baby my heart could still fall as hard at 23.", "Thinking Out Loud"},
                {"And I think it’s gonna be a long, long time…’til touch down brings me ’round again to find", "Rocket Man"},
                {"The phone rings in the middle of the night, my father yells what you gonna do with your life", "Girls Just Want To Have Fun"},
                {"They told him ‘Don’t you ever come around here. Don’t want to see your face, you better disappear.'", "Beat It"},
                {"Well, you can tell by the way I use my walk, I’m a woman’s man, no time to talk.", "Stayin’ Alive"},
                {"Oh, can’t you see, you belong to me. My poor heart aches…", "Every Breath You Take"},
                {"When the day is long and the night, the night is yours alone…", "Everybody Hurts"},
                {"But I’m just a poor boy and nobody loves me… He’s just a poor boy, from a poor family, spare him his life from this monstrosity", "Bohemian Rhapsody"},
                {"Just a small town girl, livin’ in a lonely world… she took the midnight train, goin’ anywhere", "Don’t Stop Believin’"},
                {"(Time After Time)- If you fall, I will catch you, I’ll be _________. Time after time.", "Waiting"},
                {"(Total Eclipse of the Heart)- Every now and then I fall __________.", "apart"},
                {"Rah, rah, ah, ah, ah, roma, roma, ma. Gaga, ooh, la, la... want your", "Bad Romance"},
                {"(Killing Me Softly)- I heard he sang a good song, I heard he had a ________ .", "style"},
                {"(With or Without You)- Sleight of hand and twist of fate, on a bed of ______ she makes me wait. And I wait without you… with or without you", "nails"}};
        Random random = new Random();
        int num = random.nextInt(lyricList.length - 1);
        return lyricList[num];
    }

    public String[] completeQuote(){
        String [][]quoteList = {{"Frankly, my dear, I don't give a damn.", "Gone With the Wind, 1939"},
                {"I'm going to make him an offer he can't refuse.", "The Godfather"},
                {"Toto, I've got a feeling we're not in Kansas anymore.", "The Wizard of Oz"},
                {"Here's looking at you, kid.", "Casablanca"},
                {"You talking to me?", "Taxi Driver"},
                {"I love the smell of napalm in the morning.", "Apocalypse Now"},
                {"Rosebud.", "Citizen Kane"},
                {"Release the Kraken!", "Clash of the Titans (2010)"},
                {"Which would be worse, to live a monster or die as a good man?", "Shutter Island"},
                {"I know who I am. I'm the dude playing a dude disguised as another dude!", "Tropic Thunder"},
                {"That's a bingo!", "Inglorious Bastards"},
                {"That's my secret, Captain: I'm always angry.", "The Avengers"},
                {"I live my life a quarter mile at a time.", "The Fast and the Furious"},
                {"I could do this all day", "Captain America: Civil War"},
                {"This is the day you will always remember as the day you almost caught Captain Jack Sparrow!", "Pirates of the Caribbean: The Curse of the Black Pearl"},
                {"Oh what a day. What a lovely day!", "Mad Max: Fury Road"},
                {"You motorboatin' son of a b****!", "Wedding Crashers"},
                {"I'm the guy who does his job. You must be the other guy.", "The Departed"},
                {"King Kong ain't got s*** on me!", "Training Day"},
                {"Look at me. I'm the captain now.", "Captain Phillips"},
                {"I'm just one stomach flu away from my goal weight.", "The Devil Wears Prada"},
                {"I am Groot.", "Guardians of the Galaxy"},
                {"I have nipples Greg. Could you milk me?", "Meet the Parents"},
                {"With great power comes great responsiblity.", "Spider-Man"},
                {"I've been a poor man and I've been a rich man. And I choose rich every f****** time!", "The Wolf of Wall Street"},
                {"This is Sparta!", "300"},
                {"You're going to go through life thinking that girls don't like you because you're a nerd. And I want you to know, from the bottom of my heart, that won't be true. It'll be because you're an a**hole.", "The Social Network"},
                {"That is so fetch.", "Mean Girls"},
                {"You shall not pass!", "Lord of the Rings: The Fellowship of the Ring"},
                {"Chewie, we're home.", "Star Wars, Episode 7: The Force Awakens"},
                {"Are you not entertained", "Gladiator"},
                {"May the odds ever be in your favor.", "The Hunger Games"},
                {"Why so serious?", "The Dark Knight"},
                {"But what I do have are a very particular set of skills. Skills I have acquired over a very long career. Skills that make me a nightmare for people like you.", "Taken"},
                {"Just keep swimming.", "Finding Nemo"},
                {"Ogres are like onions.", "Shrek"},
                {"I just wanted to take another look at you.", "A Star is Born"},
                {"I want to play a game.", "Saw"},
                {"They called me Mr. Glass.", "Unbreakable"},
                {"I am gonna kill Bill.", "Kill Bill: Vol. 2"},
                {"For a guy with a four digit IQ, I must have missed something.", "Limitless"},
                {"Do you know what happens to a toad when it's struck by lightning? The same thing that happens to everything else.", "X-Men"},
                {"You will ride eternal, shiny and chrome.", "Mad Max: Fury Road"},
                {"I don't like sand. It's all coarse, and rough, and irritating. And it gets everywhere.", "Star Wars: Episode II - Attack of the Clones"},
                {"Honey? Where's my super suit?", "The Incredibles"},
                {"Not quite my tempo.", "Whiplash"},
                {"Now you're in the sunken place.", "Get Out"},
                {"Is this your king?", "Black Panther"},
                {"I'm gonna steal the Declaration of Independence.", "National Treasure"},
                {"Boy, that escalated quickly.", "Anchorman: The Legend of Ron Burgundy"},
                {"A million dollars isn't cool. You know what's cool? A billion dollars", "The Social Network"},
                {"I wish I knew how to quit you.", "Brokeback Mountain"},
                {"An idea is like a virus. Resilient. Highly contagious. And even the smallest seed of an idea can grow. It can grow to define or destroy you.", "Inception"},
                {"It is the quality of one’s convictions that determine success, not the number of followers.", "Harry Potter and the Deathly Hallows: Part 2 "},
                {"A hero can be anyone. Even a man doing something as simple and reassuring as putting a coat around a young boy’s shoulders to let him know that the world hadn’t ended.", "The Dark Knight Rises"},
                {"I suppose, in the end, the whole of life becomes an act of letting go. But what always hurts the most is not taking a moment to say goodbye.", "Life of Pi"},
                {"Gentlemen, you had my curiosity, but now you have my attention.", "Django Unchained"},
                {"The needs of the many outweigh the needs of the few.", "Star Trek Into Darkness"},
                {"If history has proven anything, it is that evolution always wins.", "Man of Steel"},
                {"A wise man gets more from his enemies than a fool from his friends.", "Rush"},
                {"Some people are worth melting for.", "Frozen"},
                {"Crazy thing about people, the more you say no, the more they want in.", "American Hustle"},
                {"There are no two words in the English language more harmful than good job.", "Whiplash"},
                {"Ideals are peaceful. History is violent.", "Fury"},
                {"Hardest time to lie to somebody is when they’re expecting to be lied to.", "The Imitation Game"},
                {"Keep your friends rich, and your enemies rich, and wait to find out which is which.", "Avengers: Age of Ultron"},
                {"You really only need to hang mean bastards. But mean bastards, you need to hang.", "The Hateful Eight"},
                {"Life is an endless series of train wrecks with only brief commercial-like breaks of happiness.", "Deadpool"},
                {"Our very strength invites challenge. Challenge incites conflict. And conflict breeds catastrophe.", "Captain America: Civil War"},
                {"With the world so set on tearing itself apart, it don’t seem like such a bad thing to me to wanna put a little bit of it back together.", "Hacksaw Ridge"},
                {"You cannot beat a river into submission. You have to surrender to its current and use its power as your own.", "Doctor Strange"},
                {"People love what other people are passionate about.", "La La Land"},
                {"When you’re ugly, and someone loves you, you know they love you for who you are. Beautiful people never know who to trust.", "Guardians of the Galaxy Vol. 2"},
                {"The hardest choices require the strongest wills.", "Avengers: Infinity War"},
                {"They say money can’t buy happiness, darlings! But it does allow you to give it away!", "Bohemian Rhapsody"},
                {"The worst part about having a mental illness is people expect you to behave as if you don’t.", "Joker"},
                {"Always charge a guy with a gun. With a knife, you run away.", "The Irishman"},
                {"Show me the money!", "Jerry Maguire"},
//                {"I'm walking here! I'm walking here!", "Midnight Cowboy"},
                {"You can't handle the truth!" , "A Few Good Men"},
//                {"I'll have what she's having.", "When Harry Met Sally"},
                {"You're gonna need a bigger boat.", "Jaws"},
                {"I'll be back.", "The Terminator"},
                {"Mama always said life was like a box of chocolates. You never know what you're gonna get.", "Forrest Gump"},
//                {"We rob banks.", "Bonnie and Clyde"},
                {"I see dead people." , "The Sixth Sense"},
                {"We'll always have Paris.", "Casablanca"},
                {"Stella! Hey, Stella!" , "A Streetcar Named Desire"},
                {"It's alive! It's alive!", "Frankenstein"},
                {"Houston, we have a problem.", "Apollo 13"},
                {"You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?", "Dirty Harry"},
                {"You had me at hello.", "Jerry Maguire"},
//                {"There's no crying in baseball!", "A League of Their Own"},
//                {"A boy's best friend is his mother.", "Psycho"},
                {"Greed, for lack of a better word, is good.", "Wall Street"},
                {"Keep your friends close, but your enemies closer.", "Godfather Part 2"},
                {"Say hello to my little friend!", "Scarface"},
                {"Get your stinking paws off me, you damned dirty ape.", "Planet of the Apes"},
                {"Here's Johnny!", "The Shinning"},
                {"Hasta la vista, baby.", "Terminator 2"},
                {"Yo, Adrian!", "Rocky"},
                {"Oh, no, it wasn't the airplanes. It was Beauty killed the Beast.", "King Kong"},
                {"My precious." , "Lord of the Rings: Two Towers"},
                {"A martini. Shaken, not stirred.", "Goldfinger"},
                {"I feel the need - the need for speed!", "Top Gun"},
                {"Carpe diem. Seize the day, boys. Make your lives extraordinary.", "Dead Poets Society"},
                {"Nobody puts Baby in a corner.", "Dirty Dancing"},
                {"I'm king of the world!", "Titanic"},
                {"Roads? Where we're going we don't need roads.", "Back to the Future"},
                {"That'll do, pig. That'll do.", "Babe"},
                {"Inconceivable!", "The Princess Bride"},
                {"They may take our lives, but they'll never take our freedom!", "Braveheart"},
                {"To infinity and beyond!", "Toy Story"}};
        Random random = new Random();
        int num = random.nextInt(quoteList.length - 1);
        return quoteList[num];
    }
}
